'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Flow.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BgImage1024x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BgImage1024x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BgImageLarge1024x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BgImageLarge1024x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BgInput() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BgInput", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonKeyIndicator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonKeyIndicator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;XmlTheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; ThemeName=&quot;ButtonTheme&quot;&gt;
        '''  &lt;BuilderRegistrations&gt;
        '''    &lt;XmlStyleBuilderRegistration&gt;
        '''      &lt;BuilderData xsi:type=&quot;XmlStyleSheet&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''        &lt;PropertySettingGroups&gt;
        '''          &lt;XmlPropertySettingGroup&gt;
        '''            &lt;PropertySettings&gt;
        '''              &lt;XmlAnimatedPropertySetting StartValueIsCurrentValue=&quot;False&quot; EndValue=&quot;158, 37, 37&quot; Property=&quot;Telerik.Win [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ButtonTheme() As String
            Get
                Return ResourceManager.GetString("ButtonTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;XmlTheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; ThemeName=&quot;Pix36KeyLabelTheme&quot;&gt;
        '''  &lt;BuilderRegistrations&gt;
        '''    &lt;XmlStyleBuilderRegistration&gt;
        '''      &lt;BuilderData xsi:type=&quot;XmlStyleSheet&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''        &lt;PropertySettingGroups&gt;
        '''          &lt;XmlPropertySettingGroup&gt;
        '''            &lt;PropertySettings&gt;
        '''              &lt;XmlPropertySetting Property=&quot;Telerik.WinControls.VisualElement.Font&quot; Value=&quot;Calibri, 36pt, style= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property frmUIkeyLabel() As String
            Get
                Return ResourceManager.GetString("frmUIkeyLabel", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property iconLargeAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLargeAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLargeExclamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLargeExclamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLargeHelp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLargeHelp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLargeHome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLargeHome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLargeMinimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLargeMinimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLargeSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLargeSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallDone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallDone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallHelp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallHelp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallKeyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallKeyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconSmallRecyclebin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSmallRecyclebin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property keyHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KeyIndicatorBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeyIndicatorBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;XmlTheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; ThemeName=&quot;LabelTheme&quot;&gt;
        '''  &lt;BuilderRegistrations&gt;
        '''    &lt;XmlStyleBuilderRegistration&gt;
        '''      &lt;BuilderData xsi:type=&quot;XmlStyleSheet&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''        &lt;PropertySettingGroups&gt;
        '''          &lt;XmlPropertySettingGroup&gt;
        '''            &lt;PropertySettings&gt;
        '''              &lt;XmlPropertySetting Property=&quot;Telerik.WinControls.VisualElement.Font&quot; Value=&quot;Calibri, 48pt, style=Bold&quot; /&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LabelTheme() As String
            Get
                Return ResourceManager.GetString("LabelTheme", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Logo500x500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo500x500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogoSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuButtonHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuButtonHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Notification() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Notification", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property OSK_1024x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OSK_1024x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;XmlTheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; ThemeName=&quot;SmallButtonTheme&quot;&gt;
        '''  &lt;BuilderRegistrations&gt;
        '''    &lt;XmlStyleBuilderRegistration&gt;
        '''      &lt;BuilderData xsi:type=&quot;XmlStyleSheet&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''        &lt;PropertySettingGroups&gt;
        '''          &lt;XmlPropertySettingGroup&gt;
        '''            &lt;PropertySettings&gt;
        '''              &lt;XmlAnimatedPropertySetting StartValueIsCurrentValue=&quot;False&quot; EndValue=&quot;158, 37, 37&quot; Property=&quot;Teleri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SmallButtonTheme() As String
            Get
                Return ResourceManager.GetString("SmallButtonTheme", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SoundAlert() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundAlert", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SoundChangeLayout() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundChangeLayout", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SoundClick() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundClick", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SoundStartup() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoundStartup", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;XmlTheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; ThemeName=&quot;New Theme&quot;&gt;
        '''  &lt;BuilderRegistrations&gt;
        '''    &lt;XmlStyleBuilderRegistration&gt;
        '''      &lt;BuilderData xsi:type=&quot;XmlStyleSheet&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''        &lt;PropertySettingGroups&gt;
        '''          &lt;XmlPropertySettingGroup&gt;
        '''            &lt;PropertySettings&gt;
        '''              &lt;XmlPropertySetting Property=&quot;Telerik.WinControls.Primitives.FillPrimitive.GradientStyle&quot; Value=&quot;Solid&quot; /&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ThemeListbox() As String
            Get
                Return ResourceManager.GetString("ThemeListbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;XmlTheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; ThemeName=&quot;New Theme&quot;&gt;
        '''  &lt;BuilderRegistrations&gt;
        '''    &lt;XmlStyleBuilderRegistration&gt;
        '''      &lt;BuilderData xsi:type=&quot;XmlStyleSheet&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''        &lt;PropertySettingGroups&gt;
        '''          &lt;XmlPropertySettingGroup&gt;
        '''            &lt;PropertySettings&gt;
        '''              &lt;XmlPropertySetting Property=&quot;Telerik.WinControls.Primitives.FillPrimitive.GradientStyle&quot; Value=&quot;Solid&quot; /&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ThemeListboxV2() As String
            Get
                Return ResourceManager.GetString("ThemeListboxV2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property TransparentBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransparentBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transparentLargeBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transparentLargeBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tutor_ActivateFlow2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutor_ActivateFlow2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tutor_Configpopup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutor_Configpopup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tutor_Configure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutor_Configure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tutor_Layout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutor_Layout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tutor_Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutor_Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tutor_SwitchToLayout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tutor_SwitchToLayout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
